name: Publish core via GitHub Actions

on:
  push:
    branches:
      - dev
  release:
    types: [ published ]

jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
      - uses: actions/checkout@v2
      - if: github.ref == 'refs/heads/dev'
        id: Build-Vue
        uses: xRealNeon/VuePagesAction@1.0.1
        with:
          username: 'devlive-community'
          reponame: 'shadcn-ui-vue-admin'
          token: ${{ secrets.GH_TOKEN }}
